# NumPy 
NumPy is a Linear Algebra Library for Python, it is so important for Data Science with Python because almost all of the libraries in the PyData Ecosystem rely on NumPy.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy.

### Using Numpy
Once you've installed NumPy you can import it as a library:

In [10]:
## run uv add numpy to install numpy since I use The Google Antigravity IDE
import numpy as np

### Numpy Array
Numpy arrays essentially come in two flavors: 
- vectors: 1-d arrays 
- matrices: 2-d arrays (but you should note a matrix can still have only one row or one column).

In [ ]:
## We can create an array by directly converting a list or list of lists:
my_list = [1,2,3]
my_list

np.array(my_list)

array([1, 2, 3])

In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods
There are lots of built-in ways to generate Arrays:
- array: create arrays from raw Python sequences or use built-in initialization functions
- arange: return evenly spaced values within a given interval.
- zeros and ones: generate arrays of zeros or ones
- linspace: return evenly spaced numbers over a specified interval.
- eye: creates an identity matrix
- rand: create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
- randn: return a sample (or samples) from the "standard normal" distribution.
- randint: return random integers from `low` (inclusive) to `high` (exclusive).
- reshape: returns an array containing the same data with a new shape.
- max,min,argmax,argmin: these are useful methods for finding max or min values. Or to find their index locations using argmin or argmax
- shape: an attribute that arrays have (not a method)
- dtype: check the data type of the object in the array


In [32]:
# Create a 1D array (vector) from a list
arr_1d = np.array([1, 2, 3, 4])

# Create a 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [35]:
arr_1d

array([1, 2, 3, 4])

In [36]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [30]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.random.rand(5)

array([0.97426622, 0.14669514, 0.52393315, 0.76505829, 0.18583718])

In [40]:
np.random.rand(2,3)

array([[0.51294629, 0.4563488 , 0.49174183],
       [0.55053552, 0.59076789, 0.19208164]])

In [41]:
np.random.randn(2)

array([-0.68081044,  0.10541667])

In [42]:
np.random.randn(5,5)

array([[ 2.33738855, -0.61209109,  0.30653958,  0.07634534, -1.46156786],
       [ 2.3437573 ,  0.78152347,  0.49899914, -1.44541477,  0.2204437 ],
       [-0.02705084, -0.23392541, -0.23943837, -0.79923988,  0.32531829],
       [ 0.51616939, -3.17686205, -0.65732378, -0.99157993,  0.22624666],
       [-1.03514328,  0.38070467, -0.09206019, -0.15081117,  2.07705479]])

In [43]:
np.random.randint(1,100)

92

In [45]:
np.random.randint(1,10,10)

array([5, 9, 2, 7, 9, 8, 7, 4, 1, 6], dtype=int32)

In [48]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
ranarr

array([10, 25,  5, 34, 28, 42, 22,  4, 16, 36], dtype=int32)

In [62]:
ranarr.max()

np.int32(42)

In [63]:
ranarr.min()

np.int32(4)

In [65]:
ranarr.argmax()

np.int64(5)

In [66]:
ranarr.argmin()

np.int64(7)

In [57]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr.shape

(25,)

In [59]:
arr.dtype

dtype('int64')